datasource:
  driver: org.h2.Driver
  url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
  #    url: jdbc:h2:file:./data/fileDb
  username: sa
  password:
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show-sql: true
  format_sql: true
  hbm2ddl:
    auto: update